<?php
# this file is auto-generated by bundler 2015-09-24 22:21:48
return array (
  'javascriptFoo' => 
  array (
    'md5' => '33e7f1549ea0723bef1b6b00b598f088',
    'max' => 'package/www/builds/javascriptFoo.max.js',
    'min' => 'package/www/builds/javascriptFoo.min.js',
  ),
  'javascriptBar' => 
  array (
    'md5' => '2a67cba66ac6737aa98d5bf79b78891f',
    'max' => 'package/www/builds/javascriptBar.max.js',
    'min' => 'package/www/builds/javascriptBar.min.js',
  ),
);