<?php
# this file is auto-generated by bundler 2015-09-24 22:25:25
return array (
  'stylesheetFoo' => 
  array (
    'md5' => 'e62ee3289506144e4a2c7158202db4da',
    'max' => 'site/www/builds/stylesheetFoo.max.css',
    'min' => 'site/www/builds/stylesheetFoo.min.css',
  ),
  'stylesheetBar' => 
  array (
    'md5' => 'a21d8c42c6d63bbadc0c9aa9d371aaf2',
    'max' => 'site/www/builds/stylesheetBar.max.css',
    'min' => 'site/www/builds/stylesheetBar.min.css',
  ),
);